/* error handling in js */
function foo(){
    //try catch block
    try{
        // ...
    }catch(e){
        //catch error
        //....
    }
    }